### ISSUE TITLE
Music tracks not available

### ISSUE THREAD

**Issue by Unargent** [eukara/freehl#5]
Half-Life music tracks are no longer available on YouTube. You need to replace them with others or remove them from the Shareware installation script.

**Comment by eukara** [comment]
Thanks for bringing this up.
I've removed the action from the script. 

Some additional background: I chose not to replace the tracks because the shareware data script is solely meant to fetch data that Valve decided to release themselves without a price-tag/authentication. Maybe when they figure their licensing out (their tracks had copyright claims regarding sampling) it can come back. I'm sorry to anyone affected by this.

Workarounds:
If you need a simpler way of getting the tracks and you have an install of Half-Life's Steam version, you can copy the `valve/media` folder over into the FreeHL `valve` directory and setting `seta cl_musicstyle 2` in the console.
That will ensure to look for the Steam Half-Life tracks instead of the RedBook tracks inside `music/trackXX.ogg`.

If you have .flac versions of the tracks then `seta cl_musicstyle 1` will play those back too inside `music/trackXX.flac` - but you need the ffmpeg plugin for FTEQW installed.

**Comment by SirYodaJedi** [comment]
The official uploads actually are [still on YouTube](https://youtube.com/playlist?list=OLAK5uy_mP4d7DekRBW9GoV573TUMtZhUdA5spsKk).

`cl_musicstyle 2` is definitely the easier option, though (don't even need to own a GoldSrc game; can just install the Half-Life Dedicated Server app on Steam).
